### ISSUE TITLE
newPage() requires arguments

### ISSUE THREAD

**Issue by jansindl3r** [justvanrossum/drawbot-skia#13]
`newPage()` requires argument, though mac's drawbot doesn't. This breaks compatibility of code that can be shared in class for both drawbot app and drawbot-skia. Is it intentional? Can I make a PR?

**Comment by justvanrossum** [comment]
It's in between intentional and an oversight... (I'm not super happy with the argument-less version, but let's make it compatible.)

A PR would be great! Best with a test case.

- Initial newPage() without arguments: 1000 x 1000
- Second newPage() without arguments: same as previous page

Thanks.

**Comment by jansindl3r** [comment]
Well the test fails with pdfs, f.e. arcTo.pdf differ on 4th byte. 

expected:b'<</Producer (Skia/PDF m87)>>\n'
output:b'<</Producer (Skia/PDF m86)>>\n'

**Comment by justvanrossum** [comment]
> so just update skia, I guess :)

Yes `pip install --upgrade skia-python` please :)

I've been meaning to make the tests accept these differences, but didn't manage yet.

**Comment by justvanrossum** [comment]
Fixed with 0bc14c38e00b61fbb80027ece7220c9a5650b930
