### ISSUE TITLE
integration in jupyter notebook?

### ISSUE THREAD

**Issue by joachimheintz** [justvanrossum/drawbot-skia#53]
hi and thanks for the great work.  i installed it yesterday on debian and everything seems to work well.

is there any way to integrate it in a jupyter notebook, as it is the case for the matplotlib?  or what is your normal workflow in coding and watching the result?

cheers -
  joachim

**Comment by justvanrossum** [comment]
I personally run a script, and then open the exported image.

I know nothing about Jupyter notebooks, but I'm open to suggestions how to make integration possible.

**Comment by joachimheintz** [comment]
i found an easy method which 
1. works with a script file in one jupter tab, and
2. renders and displays the result in another one.
[Drawbot-skia.pdf](https://github.com/justvanrossum/drawbot-skia/files/7785252/Drawbot-skia.pdf)
i think it might be possible to render a code cell directly to an image which is shown in the cell output, but i don't know how, and the workflow above is ok for me now.

**Comment by joachimheintz** [comment]
just to add an update which uses the '%%writefile' in a cell to write in the same notebook.
it can be downloaded [here](https://github.com/joachimheintz/drawbot_skia/blob/main/220129_workflow.ipynb)
![drawbot_skia_2](https://user-images.githubusercontent.com/2196394/151674652-cfc65f60-ba50-452f-b247-6716c9f1c087.png)
